export const assetPortfolioData = [
  {
    "srNo": "01",
    "equipment": "Rack -1",
    "serialNo": "TJS-0097-0097",
    "condition": "Semi-damaged",
    "status": "In Use",
    "blockLocation": "Bhudhana",
    "blockCode": "274063",
    "siteType": "Off Site",
    "warranty": "Yes",
    "requestFor": "Replacement"
  },
  {
    "srNo": "02",
    "equipment": "Rack -2",
    "serialNo": "TJS-8961-0098",
    "condition": "Robust",
    "status": "Not in Use",
    "blockLocation": "Bhudhana",
    "blockCode": "268678",
    "siteType": "Native Site",
    "warranty": "Yes",
    "requestFor": "-"
  },
  {
    "srNo": "03",
    "equipment": "SMPS",
    "serialNo": "HIS-7892-0099",
    "condition": "Robust",
    "status": "In Use",
    "blockLocation": "Bhudhana",
    "blockCode": "268653",
    "siteType": "Native Site",
    "warranty": "Yes",
    "requestFor": "Maintenance"
  },
  {
    "srNo": "04",
    "equipment": "CCU -1",
    "serialNo": "TJS-6719-0100",
    "condition": "Damaged",
    "status": "Not in Use",
    "blockLocation": "Baghara",
    "blockCode": "81093",
    "siteType": "Off Site",
    "warranty": "No",
    "requestFor": "-"
  },
  {
    "srNo": "05",
    "equipment": "CCU -2",
    "serialNo": "IOD-2899-1097",
    "condition": "Robust",
    "status": "Not in Use",
    "blockLocation": "Baghara",
    "blockCode": "81094",
    "siteType": "Assigned Site",
    "warranty": "Yes",
    "requestFor": "-"
  },
  {
    "srNo": "06",
    "equipment": "CCU -3",
    "serialNo": "TIS-0097-1078",
    "condition": "Robust",
    "status": "In Use",
    "blockLocation": "Baghara",
    "blockCode": "81095",
    "siteType": "Assigned Site",
    "warranty": "Yes",
    "requestFor": "-"
  },
  {
    "srNo": "07",
    "equipment": "CCU -4",
    "serialNo": "TJS-0097-1063",
    "condition": "Robust",
    "status": "Not in Use",
    "blockLocation": "Atrauli",
    "blockCode": "81096",
    "siteType": "Assigned Site",
    "warranty": "Yes",
    "requestFor": "-"
  },
  {
    "srNo": "08",
    "equipment": "FDMS-1",
    "serialNo": "OPF-0097-2063",
    "condition": "Robust",
    "status": "Not in Use",
    "blockLocation": "Atrauli",
    "blockCode": "81097",
    "siteType": "Native Site",
    "warranty": "Yes",
    "requestFor": "Maintenance"
  },
  {
    "srNo": "09",
    "equipment": "Patchcord",
    "serialNo": "YID-6919-0097",
    "condition": "Semi-damaged",
    "status": "In Use",
    "blockLocation": "Atrauli",
    "blockCode": "274068",
    "siteType": "Native Site",
    "warranty": "No",
    "requestFor": "Maintenance"
  },
  {
    "srNo": "10",
    "equipment": "Battery",
    "serialNo": "JSK-7281-8917",
    "condition": "Damaged",
    "status": "Not in Use",
    "blockLocation": "Atrauli",
    "blockCode": "81098",
    "siteType": "Native Site",
    "warranty": "No",
    "requestFor": "Replacement"
  }
]

export const blockWiseAssetTableData = [
  {
    "srNo": "01",
    "block": "Bhudhana",
    "blockCode": "",
    "district": "Muzaffarnagar",
    "districtCode": ""
  },
  {
    "srNo": "02",
    "block": "Bhudhana",
    "blockCode": "",
    "district": "Muzaffarnagar",
    "districtCode": ""
  },
  {
    "srNo": "03",
    "block": "Bhudhana",
    "blockCode": "",
    "district": "Muzaffarnagar",
    "districtCode": ""
  },
  {
    "srNo": "04",
    "block": "Baghara",
    "blockCode": "",
    "district": "Muzaffarnagar",
    "districtCode": ""
  },
  {
    "srNo": "05",
    "block": "Baghara",
    "blockCode": "",
    "district": "Muzaffarnagar",
    "districtCode": ""
  },
  {
    "srNo": "06",
    "block": "Baghara",
    "blockCode": "",
    "district": "Muzaffarnagar",
    "districtCode": ""
  },
  {
    "srNo": "07",
    "block": "Atrauli",
    "blockCode": "",
    "district": "Aligarh",
    "districtCode": ""
  },
  {
    "srNo": "08",
    "block": "Atrauli",
    "blockCode": "",
    "district": "Aligarh",
    "districtCode": ""
  },
  {
    "srNo": "09",
    "block": "Atrauli",
    "blockCode": "",
    "district": "Aligarh",
    "districtCode": ""
  },
  {
    "srNo": "10",
    "block": "Akrabad",
    "blockCode": "",
    "district": "Aligarh",
    "districtCode": ""
  }
]

export const maintenanceTableData = [
  {
    srNo: "01",
    id: "VLZ-452",
    requestDate: "VLZ1400087402",
    equipment: "Post launch reminder/ post list",
    serialno: "Joseph Parker",
    blockCode: "268653",
    repairType: "Alexis Clarke",
    allocatedTo: "Joseph Parker",
    assignedTo: "03 Oct, 2021",
    issueReported: "Re-open",
    repairDays: "Damaged",
    issueDate:"Edit customer",
    eta: "12/04/2025",
    status: "Installed",
    document: "file.jpeg",
    remark: " "
  },
  {
    srNo: "01",
    id: "VLZ-452",
    requestDate: "VLZ1400087402",
    equipment: "Post launch reminder/ post list",
    serialno: "Joseph Parker",
    blockCode: "268653",
    repairType: "Alexis Clarke",
    allocatedTo: "Joseph Parker",
    assignedTo: "03 Oct, 2021",
    issueReported: "Re-open",
    repairDays: "Damaged",
    issueDate:"Edit customer",
    eta: "12/04/2025",
    status: "Assigned",
    document: "file.jpeg",
    remark: " "
  },
  {
    srNo: "01",
    id: "VLZ-452",
    requestDate: "VLZ1400087402",
    equipment: "Post launch reminder/ post list",
    serialno: "Joseph Parker",
    blockCode: "268653",
    repairType: "Alexis Clarke",
    allocatedTo: "Joseph Parker",
    assignedTo: "03 Oct, 2021",
    issueReported: "Re-open",
    repairDays: "Damaged",
    issueDate:"Edit customer",
    eta: "12/04/2025",
    status: "Installed",
    document: "file.jpeg",
    remark: " "
  },
  {
    srNo: "01",
    id: "VLZ-452",
    requestDate: "VLZ1400087402",
    equipment: "Post launch reminder/ post list",
    serialno: "Joseph Parker",
    blockCode: "268653",
    repairType: "Alexis Clarke",
    allocatedTo: "Joseph Parker",
    assignedTo: "03 Oct, 2021",
    issueReported: "Re-open",
    repairDays: "Damaged",
    issueDate:"Edit customer",
    eta: "12/04/2025",
    status: "Under-repair",
    document: "file.jpeg",
    remark: " "
  },
  {
    srNo: "01",
    id: "VLZ-452",
    requestDate: "VLZ1400087402",
    equipment: "Post launch reminder/ post list",
    serialno: "Joseph Parker",
    blockCode: "268653",
    repairType: "Alexis Clarke",
    allocatedTo: "Joseph Parker",
    assignedTo: "03 Oct, 2021",
    issueReported: "Re-open",
    repairDays: "Damaged",
    issueDate:"Edit customer",
    eta: "12/04/2025",
    status: "Under-repair",
    document: "file.jpeg",
    remark: " "
  },
  {
    srNo: "01",
    id: "VLZ-452",
    requestDate: "VLZ1400087402",
    equipment: "Post launch reminder/ post list",
    serialno: "Joseph Parker",
    blockCode: "268653",
    repairType: "Alexis Clarke",
    allocatedTo: "Joseph Parker",
    assignedTo: "03 Oct, 2021",
    issueReported: "Re-open",
    repairDays: "Damaged",
    issueDate:"Edit customer",
    eta: "12/04/2025",
    status: "Under-repair",
    document: "file.jpeg",
    remark: " "
  },
  { 
    srNo: "01",
    id: "VLZ-452",
    requestDate: "VLZ1400087402",
    equipment: "Post launch reminder/ post list",
    serialno: "Joseph Parker",
    blockCode: "268653",
    repairType: "Alexis Clarke",
    allocatedTo: "Joseph Parker",
    assignedTo: "03 Oct, 2021",
    issueReported: "Re-open",
    repairDays: "Damaged",
    issueDate:"Edit customer",
    eta: "12/04/2025",
    status: "Not assigned",
    document: "file.jpeg",
    remark: " "
  },
  {
    srNo: "01",
    id: "VLZ-452",
    requestDate: "VLZ1400087402",
    equipment: "Post launch reminder/ post list",
    serialno: "Joseph Parker",
    blockCode: "268653",
    repairType: "Alexis Clarke",
    allocatedTo: "Joseph Parker",
    assignedTo: "03 Oct, 2021",
    issueReported: "Re-open",
    repairDays: "Damaged",
    issueDate:"Edit customer",
    eta: "12/04/2025",
    status: "Under-repair",
    document: "file.jpeg",
    remark: " "
  },
]

export const replacemnetData = [
  {
    "srNo": 1,
    "id": "REPL–240415",
    "requestDate": "11/04/2025",
    "equipment": "Rack –10",
    "serialNo": "TJS–0097–0097",
    "blockCode": "268653",
    "replacementReason": "Damaged",
    "issueDate": "11/04/2025",
    "eta": "12/04/2025",
    "initiatedBy": "Vijayent",
    "newSerialNo": "TJS–0097–1099",
    "status": "Installed",
    "document": "file.jpg",
    "remarks": "-"
  },
  {
    "srNo": 2,
    "id": "REPL–240416",
    "requestDate": "12/04/2025",
    "equipment": "Rack –11",
    "serialNo": "TJS–8961–0098",
    "blockCode": "268678",
    "replacementReason": "Damaged",
    "issueDate": "12/04/2025",
    "eta": "13/04/2025",
    "initiatedBy": "Nirmal",
    "newSerialNo": "TJS–0097–1089",
    "status": "In-transit",
    "document": "file.jpg",
    "remarks": "-"
  },
  {
    "srNo": 3,
    "id": "REPL–240417",
    "requestDate": "12/04/2025",
    "equipment": "Rack –12",
    "serialNo": "HIS–7892–0099",
    "blockCode": "268700",
    "replacementReason": "Damaged",
    "issueDate": "12/04/2025",
    "eta": "14/04/2025",
    "initiatedBy": "Ramesh Rao",
    "newSerialNo": "TJS–0097–1100",
    "status": "Installed",
    "document": "file.jpg",
    "remarks": "-"
  },
  {
    "srNo": 4,
    "id": "REPL–240418",
    "requestDate": "12/04/2025",
    "equipment": "CCU –11",
    "serialNo": "TJS–6719–0100",
    "blockCode": "274063",
    "replacementReason": "Damaged",
    "issueDate": "12/04/2025",
    "eta": "-",
    "initiatedBy": "Pradeep",
    "newSerialNo": "",
    "status": "In transit",
    "document": "file.jpg",
    "remarks": "-"
  },
  {
    "srNo": 5,
    "id": "REPL–240419",
    "requestDate": "13/04/2025",
    "equipment": "CCU –12",
    "serialNo": "IOD–2899–1097",
    "blockCode": "81093",
    "replacementReason": "Damaged",
    "issueDate": "13/04/2025",
    "eta": "-",
    "initiatedBy": "Pranab",
    "newSerialNo": "",
    "status": "Received",
    "document": "file.jpg",
    "remarks": "-"
  },
  {
    "srNo": 6,
    "id": "REPL–240420",
    "requestDate": "14/04/2025",
    "equipment": "CCU –13",
    "serialNo": "TIS–0097–1078",
    "blockCode": "81094",
    "replacementReason": "Damaged",
    "issueDate": "14/04/2025",
    "eta": "15/04/2025",
    "initiatedBy": "Parveen",
    "newSerialNo": "TJS–0097–1240",
    "status": "Installed",
    "document": "file.jpg",
    "remarks": "-"
  },
  {
    "srNo": 7,
    "id": "REPL–240421",
    "requestDate": "15/04/2025",
    "equipment": "CCU –14",
    "serialNo": "TJS–0097–1063",
    "blockCode": "81095",
    "replacementReason": "Damaged",
    "issueDate": "15/04/2025",
    "eta": "-",
    "initiatedBy": "Kartik",
    "newSerialNo": "",
    "status": "In-transit",
    "document": "file.jpg",
    "remarks": "-"
  },
  {
    "srNo": 8,
    "id": "REPL–240422",
    "requestDate": "14/04/2025",
    "equipment": "FDMS–16",
    "serialNo": "OPF–0097–2063",
    "blockCode": "81096",
    "replacementReason": "Damaged",
    "issueDate": "14/04/2025",
    "eta": "16/04/2025",
    "initiatedBy": "Abhinav Chirag",
    "newSerialNo": "TJS–0097–1249",
    "status": "Assigned",
    "document": "file.jpg",
    "remarks": "-"
  },
  {
    "srNo": 9,
    "id": "REPL–240423",
    "requestDate": "15/04/2025",
    "equipment": "FDMS–17",
    "serialNo": "YID–6919–0097",
    "blockCode": "81097",
    "replacementReason": "Damaged",
    "issueDate": "15/04/2025",
    "eta": "17/04/2025",
    "initiatedBy": "Aayushman",
    "newSerialNo": "TJS–0097–1247",
    "status": "Not assigned",
    "document": "file.jpg",
    "remarks": "-"
  },
  {
    "srNo": 10,
    "id": "REPL–240424",
    "requestDate": "16/04/2025",
    "equipment": "FDMS–18",
    "serialNo": "JSK–7281–8917",
    "blockCode": "81098",
    "replacementReason": "Damaged",
    "issueDate": "16/04/2025",
    "eta": "-",
    "initiatedBy": "Aayushi",
    "newSerialNo": "",
    "status": "Received",
    "document": "file.jpg",
    "remarks": "-"
  }
]

export const transferData = [
  {
    "srNo": "01",
    "id": "TRN-240415",
    "requestDate": "12/04/2025",
    "equipment": "Rack -10",
    "serialNo": "TJS-0097-0097",
    "transferType": "Internal",
    "transferForm": "274063",
    "trasnferTo": "274063",
    "initiatedBy": "Vijayent",
    "issueDate": "11/04/2025",
    "status": "Installed",
    "document": "customer",
    "remarks": "-"
  },
  {
    "srNo": "02",
    "id": "TRN-240416",
    "requestDate": "13/04/2025",
    "equipment": "Rack -11",
    "serialNo": "TJS-8961-0098",
    "transferType": "Internal",
    "transferForm": "268678",
    "trasnferTo": "268678",
    "initiatedBy": "Nirmal",
    "issueDate": "12/04/2025",
    "status": "Received",
    "document": "customer",
    "remarks": "-"
  },
  {
    "srNo": "03",
    "id": "TRN-240417",
    "requestDate": "14/04/2025",
    "equipment": "Rack -12",
    "serialNo": "HIS-7892-0099",
    "transferType": "Internal",
    "transferForm": "268653",
    "trasnferTo": "268653",
    "initiatedBy": "Ramesh Rao",
    "issueDate": "12/04/2025",
    "status": "Installed",
    "document": "customer",
    "remarks": "-"
  },
  {
    "srNo": "04",
    "id": "TRN-240418",
    "requestDate": "14/04/2025",
    "equipment": "CCU -11",
    "serialNo": "TJS-6719-0100",
    "transferType": "Internal",
    "transferForm": "81093",
    "trasnferTo": "81093",
    "initiatedBy": "Pradeep",
    "issueDate": "12/04/2025",
    "status": "In transit",
    "document": "customer",
    "remarks": "-"
  },
  {
    "srNo": "05",
    "id": "TRN-240419",
    "requestDate": "15/04/2025",
    "equipment": "CCU -12",
    "serialNo": "IOD-2899-1097",
    "transferType": "Internal",
    "transferForm": "81094",
    "trasnferTo": "81094",
    "initiatedBy": "Pranab",
    "issueDate": "13/04/2025",
    "status": "In-transit",
    "document": "customer",
    "remarks": "-"
  },
  {
    "srNo": "06",
    "id": "TRN-240420",
    "requestDate": "15/04/2025",
    "equipment": "CCU -13",
    "serialNo": "TIS-0097-1078",
    "transferType": "External",
    "transferForm": "274064",
    "trasnferTo": "80100",
    "initiatedBy": "Parveen",
    "issueDate": "14/04/2025",
    "status": "Installed",
    "document": "customer",
    "remarks": "-"
  },
  {
    "srNo": "07",
    "id": "TRN-240421",
    "requestDate": "16/04/2025",
    "equipment": "CCU -14",
    "serialNo": "TJS-0097-1063",
    "transferType": "External",
    "transferForm": "274079",
    "trasnferTo": "80100",
    "initiatedBy": "Kartik",
    "issueDate": "15/04/2025",
    "status": "In-transit",
    "document": "customer",
    "remarks": "-"
  },
  {
    "srNo": "08",
    "id": "TRN-240422",
    "requestDate": "16/04/2025",
    "equipment": "FDMS-16",
    "serialNo": "OPF-0097-2063",
    "transferType": "External",
    "transferForm": "374054",
    "trasnferTo": "80100",
    "initiatedBy": "Abhinav Chirag",
    "issueDate": "14/04/2025",
    "status": "Assigned",
    "document": "customer",
    "remarks": "-"
  },
  {
    "srNo": "09",
    "id": "TRN-240423",
    "requestDate": "17/04/2025",
    "equipment": "FDMS-17",
    "serialNo": "YID-6919-0097",
    "transferType": "External",
    "transferForm": "274068",
    "trasnferTo": "80100",
    "initiatedBy": "Aayushman",
    "issueDate": "15/04/2025",
    "status": "Not assigned",
    "document": "customer",
    "remarks": "-"
  },
  {
    "srNo": "10",
    "id": "TRN-240424",
    "requestDate": "17/04/2025",
    "equipment": "FDMS-18",
    "serialNo": "JSK-7281-8917",
    "transferType": "External",
    "transferForm": "374063",
    "trasnferTo": "80100",
    "initiatedBy": "Aayushi",
    "issueDate": "16/04/2025",
    "status": "Received",
    "document": "customer",
    "remarks": "-"
  }
]