export const assetPortfolioData = [
  {
    srNo: "01",
    equipment: "Post launch reminder/ post list",
    serialNo: "TJS-0097-0097",
    condition: "Semi-Damaged",
    status: "In Use",
    blockLocation: "Bhudhana",
    blockCode: "268653",
    siteType: "Native Site",
    warranty: "Yes",
  },
  {
    srNo: "02",
    equipment: "Additional Calendar",
    serialNo: "TJS-0097-0098",
    condition: "Robust",
    status: "Not in Use",
    blockLocation: "Bhudhana",
    blockCode: "268678",
    siteType: "Native Site",
    warranty: "Yes",
  },
  {
    srNo: "03",
    equipment: "Make a creating an account profile",
    serialNo: "HIS-7892-0099",
    condition: "Robust",
    status: "In Use",
    blockLocation: "Bhudhana",
    blockCode: "268700",
    siteType: "Native Site",
    warranty: "Yes",
  },
  {
    srNo: "04",
    equipment: "Apologize for shopping Error!",
    serialNo: "TJS-6719-0100",
    condition: "Damaged",
    status: "Not in Use",
    blockLocation: "Baghara",
    blockCode: "274063",
    siteType: "Off Site",
    warranty: "Yes",
  },
  {
    srNo: "05",
    equipment: "Support for theme",
    serialNo: "IOD-2899-1097",
    condition: "Robust",
    status: "Not in Use",
    blockLocation: "Baghara",
    blockCode: "81093",
    siteType: "Off Site",
    warranty: "No",
  },
  {
    srNo: "07",
    equipment: "Change email option process",
    serialNo: "TJS-0097-1078",
    condition: "Robust",
    status: "In Use",
    blockLocation: "Baghara",
    blockCode: "81094",
    siteType: "Assigned Site",
    warranty: "Yes",
  },
  {
    srNo: "08",
    equipment: "Support for theme",
    serialNo: "TJS-0097-1063",
    condition: "Robust",
    status: "In Use",
    blockLocation: "Atrauli",
    blockCode: "81095",
    siteType: "Assigned Site",
    warranty: "Yes",
  },
  {
    srNo: "09",
    equipment: "Form submit issue",
    serialNo: "OPF-0097-2063",
    condition: "Robust",
    status: "Not in Use",
    blockLocation: "Atrauli",
    blockCode: "81096",
    siteType: "Native Site",
    warranty: "Yes",
  },
  {
    srNo: "10",
    equipment: "Edit customer testimonial",
    serialNo: "YID-6919-0097",
    condition: "Semi-Damaged",
    status: "In Use",
    blockLocation: "Atrauli",
    blockCode: "81097",
    siteType: "Native Site",
    warranty: "Yes",
  },
  {
    srNo: "11",
    equipment: "Ca i have an e-copy invoice",
    serialNo: "JSK-7281-8917",
    condition: "Damaged",
    status: "Not in Use",
    blockLocation: "Atrauli",
    blockCode: "81098",
    siteType: "Native Site",
    warranty: "No",
  },
  {
    srNo: "12",
    equipment: "Brand logo design",
    serialNo: "TJS-0097-0097",
    condition: "Semi-Damaged",
    status: "In Use",
    blockLocation: "Bhudhana",
    blockCode: "268653",
    siteType: "Native Site",
    warranty: "Yes",
  },
  {
    srNo: "13",
    equipment: "Issue with finding information about order ?",
    serialNo: "TJS-0097-0098",
    condition: "Robust",
    status: "Not in Use",
    blockLocation: "Bhudhana",
    blockCode: "268678",
    siteType: "Native Site",
    warranty: "Yes",
  },
  {
    srNo: "14",
    equipment: "Make a creating an account profile",
    serialNo: "HIS-7892-0099",
    condition: "Robust",
    status: "In Use",
    blockLocation: "Bhudhana",
    blockCode: "268700",
    siteType: "Native Site",
    warranty: "Yes",
  },
];

export const blockWiseAssetData = [
  {
    srNo: "01",
    equipment: "Post launch reminder/ post list",
    serialNo: "TJS-0097-0097",
    condition: "Semi-Damaged",
    status: "In Use",
    blockLocation: "Bhudhana",
    blockCode: "268653",
    siteType: "Native Site",
    warranty: "Yes",
    requestedFor: "-",
    details: "info",
  },
  {
    srNo: "02",
    equipment: "Additional Calendar",
    serialNo: "TJS-0097-0098",
    condition: "Robust",
    status: "Not in Use",
    blockLocation: "Bhudhana",
    blockCode: "268678",
    siteType: "Native Site",
    warranty: "Yes",
    requestedFor: "-",
    details: "info",
  },
  {
    srNo: "03",
    equipment: "Make a creating an account profile",
    serialNo: "HIS-7892-0099",
    condition: "Robust",
    status: "In Use",
    blockLocation: "Bhudhana",
    blockCode: "268700",
    siteType: "Native Site",
    warranty: "Yes",
    requestedFor: "-",
    details: "info",
  },
  {
    srNo: "04",
    equipment: "Apologize for shopping Error!",
    serialNo: "TJS-6719-0100",
    condition: "Damaged",
    status: "Not in Use",
    blockLocation: "Baghara",
    blockCode: "274063",
    siteType: "Off Site",
    warranty: "Yes",
    requestedFor: "-",
    details: "info",
  },
  {
    srNo: "05",
    equipment: "Support for theme",
    serialNo: "IOD-2899-1097",
    condition: "Robust",
    status: "Not in Use",
    blockLocation: "Baghara",
    blockCode: "81093",
    siteType: "Off Site",
    warranty: "No",
    requestedFor: "-",
    details: "info",
  },
  {
    srNo: "07",
    equipment: "Change email option process",
    serialNo: "TJS-0097-1078",
    condition: "Robust",
    status: "In Use",
    blockLocation: "Baghara",
    blockCode: "81094",
    siteType: "Assigned Site",
    warranty: "Yes",
    requestedFor: "-",
    details: "info",
  },
  {
    srNo: "08",
    equipment: "Support for theme",
    serialNo: "TJS-0097-1063",
    condition: "Robust",
    status: "In Use",
    blockLocation: "Atrauli",
    blockCode: "81095",
    siteType: "Assigned Site",
    warranty: "Yes",
    requestedFor: "-",
    details: "info",
  },
  {
    srNo: "09",
    equipment: "Form submit issue",
    serialNo: "OPF-0097-2063",
    condition: "Robust",
    status: "Not in Use",
    blockLocation: "Atrauli",
    blockCode: "81096",
    siteType: "Native Site",
    warranty: "Yes",
    requestedFor: "-",
    details: "info",
  },
  {
    srNo: "10",
    equipment: "Edit customer testimonial",
    serialNo: "YID-6919-0097",
    condition: "Semi-Damaged",
    status: "In Use",
    blockLocation: "Atrauli",
    blockCode: "81097",
    siteType: "Native Site",
    warranty: "Yes",
    requestedFor: "-",
    details: "info",
  },
  {
    srNo: "11",
    equipment: "Ca i have an e-copy invoice",
    serialNo: "JSK-7281-8917",
    condition: "Damaged",
    status: "Not in Use",
    blockLocation: "Atrauli",
    blockCode: "81098",
    siteType: "Native Site",
    warranty: "No",
    requestedFor: "-",
    details: "info",
  },
  {
    srNo: "12",
    equipment: "Brand logo design",
    serialNo: "TJS-0097-0097",
    condition: "Semi-Damaged",
    status: "In Use",
    blockLocation: "Bhudhana",
    blockCode: "268653",
    siteType: "Native Site",
    warranty: "Yes",
    requestedFor: "Replacement",
    details: "info",
  },
  {
    srNo: "13",
    equipment: "Issue with finding information about order ?",
    serialNo: "TJS-0097-0098",
    condition: "Robust",
    status: "Not in Use",
    blockLocation: "Bhudhana",
    blockCode: "268678",
    siteType: "Native Site",
    warranty: "Yes",
    requestedFor: "Maintenance",
    details: "info",
  },
  {
    srNo: "14",
    equipment: "Make a creating an account profile",
    serialNo: "HIS-7892-0099",
    condition: "Robust",
    status: "In Use",
    blockLocation: "Bhudhana",
    blockCode: "268700",
    siteType: "Native Site",
    warranty: "Yes",
    requestedFor: "Replacement",
    details: "info",
  },
];

export const maintainceData = [];
export const replacementData = [];
export const transferData = [];